name: 'First Action'
description: 'My First action to call from remote action'
author: 'Ravi Ram'

# inputs:
#   gituser:
#     description: 'The current git user'
#     required: true
#   repositoryname:
#     description: 'Target website'
#     required: true
    
jobs:
  main:
    name: WhoCommit
    runs-on: ubuntu-latest
 
    steps:
      - run: echo *************************'
      - run: echo '*********** RaviRam first action ***************'
      - run: echo *************************'
#       - run: echo Committed by ${{github.actor}}
#       - run: echo Repository Path ${{github.repository}}
#       - run: echo Repository Name ${{ github.event.repository.name }} 
        
#       - run: echo Is RaviRamDhali
#         if: github.actor == 'RaviRamDhali'
      
#       - run: echo Is Not RaviRamDhali
#         if: github.actor != 'RaviRamDhali'
